/* Page templates. Text from editable records is escaped at the boundary. */
(() => {
  'use strict';
  const { D, Domain, icon, esc, dec, money, date, project, client, apartment, statuses, titles, state, scoped, cost, tag, qTag, avatar, btn, empty, source, reset, kv, views } = window.Dsk;
  const apartmentArt = rooms => ({ 1: './apartment-one-room-glass-v1.webp', 2: './apartment-two-room-glass-v1.webp', 3: './apartment-three-room-glass-v1.webp' }[rooms] || './apartment-two-room-glass-v1.webp');
  function apartmentCards(items) { return items.map((a, index) => { const p = project(a.projectId); return `<article class="card apartment-card compact-apartment-card"><div class="apartment-card-hero"><div class="apartment-card-copy"><div class="apartment-card-top"><span class="apartment-number">№ ${String(a.number).padStart(3, '0')}</span>${tag(a.status === 'available' ? 'Свободна' : 'В резерве', a.status === 'available' ? 'green' : 'orange', true)}</div><div class="apartment-glyph">${icon('home')}<span>${esc(p.building)}</span></div><h2>${a.rooms}-комнатная</h2><div class="apartment-area">${dec(a.area)} <span>м²</span></div><p>${esc(p.name)}</p></div><div class="apartment-card-visual"><img src="${apartmentArt(a.rooms).replace('-glass-', '-card-')}" alt="" width="${a.rooms === 1 ? 1223 : 1254}" height="${a.rooms === 1 ? 1280 : 1254}" loading="${index < 4 ? 'eager' : 'lazy'}" decoding="async"></div></div><div class="apartment-specs"><span><small>Этаж</small>${a.floor} / ${a.floors}</span><span><small>Прогноз ключей</small>${p.forecast}</span><span><small>Готовность</small>${p.progress}%</span></div><div class="apartment-price">${money(a.price)}</div><p class="apartment-rate">${money(p.price)} за м² · до скидки</p>${p.risk === 'risk' ? tag('Риск изменения срока', 'orange') : tag('Скидка до ' + p.limit + '%', 'green')}<div class="apartment-actions">${btn('apartment', 'Подробнее', 'arrow-up-right', '', `data-id="${a.id}"`)}${a.status === 'available' ? btn(D.actor.role === 'client' ? 'client-inquiry' : 'new-proposal', 'В предложение', 'plus', 'primary', `data-apartment="${a.id}"`) : `<span class="reserved-label">${icon('lock')}Забронирована</span>`}</div></article>`; }).join(''); }
  function projectSelect() {
    return `<label class="select-wrap">${icon('building')}<select id="project-filter" aria-label="Жилой комплекс"><option value="all">Все объекты</option>${D.projects.map(p => `<option value="${p.id}" ${state.project === p.id ? 'selected' : ''}>${esc(p.name)}</option>`).join('')}</select>${icon('chevron-down')}</label>`;
  }
  function heading(title, subtitle, primary = true, extra = '') {
    return `<section class="page-heading"><div><h1>${title}</h1><p>${subtitle}</p></div><div class="heading-actions">${extra}${primary ? btn('new-proposal', 'Создать КП', 'plus', 'primary') : ''}</div></section>`;
  }
  function editorialBand(kind, title, copy, pills, visualTitle, visualMeta, action = '') {
    const art = { apartments: './banner-apartments-v1.webp', proposals: './banner-proposals-v1.webp', construction: './banner-construction-v1.webp', approvals: './banner-approvals-v1.webp' }[kind];
    return `<section class="editorial-band spacious-banner ${kind}-band"><canvas class="banner-matrix" data-matrix="${kind}" aria-hidden="true"></canvas><img class="banner-full-art" src="${art}" alt="" width="820" height="547" loading="eager" fetchpriority="high" decoding="async"><div class="editorial-band-copy"><h2>${esc(title)}</h2><p>${esc(copy)}</p><div class="editorial-band-pills">${pills.slice(0, 2).map(item => `<span>${esc(item)}</span>`).join('')}</div><div class="banner-main-action">${action}</div></div></section>`;
  }
  function filterBar() {
    const r = Domain.report(state.period, state.project);
    return `<div class="filter-bar"><div class="filter-left"><div class="period-control" role="group" aria-label="Период отчёта">${[['week', 'Неделя'], ['month', 'Месяц'], ['year', 'Год']].map(([v, t]) => `<button data-period="${v}" class="${v === state.period ? 'active' : ''}" aria-pressed="${v === state.period}">${t}</button>`).join('')}</div><span class="date-range">${icon('calendar')}${r.label}</span></div><div class="filter-right">${projectSelect()}</div></div>`;
  }
  function sparkline(values) {
    const low = Math.min(...values), high = Math.max(...values), range = high - low || 1;
    const points = values.map((value, index) => `${values.length === 1 ? 50 : index / (values.length - 1) * 100},${24 - (value - low) / range * 20}`).join(' ');
    return `<svg class="stat-sparkline" viewBox="0 0 100 28" preserveAspectRatio="none" aria-hidden="true"><polyline points="${points}"/></svg>`;
  }
  function statistics() {
    const r = Domain.report(state.period, state.project);
    const proposalTotal = r.proposals.length, ready = r.proposals.filter(q => q.status === 'ready').length;
    const clientTotal = r.clients.length, reserved = r.clients.filter(c => D.apartments.some(a => a.status === 'reserved' && a.reservedBy === c.id)).length;
    const attentionTotal = r.attention.total, pending = r.attention.pending.length;
    const ratio = (value, total) => total ? Math.round(value / total * 100) : 0;
    return `<div class="stats-grid">
      <article class="stat stat-sun stat-static"><div class="stat-top"><span>Объём продаж</span><span class="stat-icon"><span class="stat-icon-copy"><small>Источник</small><strong>ERP</strong></span></span></div><div class="stat-value">${dec(r.total / 1000000)} <span>млн ₽</span></div><div class="stat-foot"><span class="delta">+${dec(r.delta)}%</span><span>к аналогичному периоду</span></div><div class="stat-micro"><span class="stat-micro-head"><span>Динамика периода</span><strong>+${dec(r.delta)}%</strong></span>${sparkline(r.current)}</div><span class="stat-serial">01 / ERP</span></article>
      <article class="stat stat-violet stat-clickable"><div class="stat-top"><span>Предложения</span><span class="stat-icon is-action"><span class="stat-icon-copy"><small>Готово</small><strong>${ready} из ${proposalTotal}</strong></span><span class="stat-affordance">${icon('arrow')}</span></span></div><div class="stat-value">${String(proposalTotal).padStart(2, '0')}</div><div class="stat-foot"><span class="delta">${ready} готовы</span><span>за выбранный период</span></div><div class="stat-micro"><span class="stat-micro-head"><span>Готовность КП</span><strong>${ratio(ready, proposalTotal)}%</strong></span><span class="stat-meter"><i style="width:${ratio(ready, proposalTotal)}%"></i></span></div><a class="stat-link" href="#proposals" aria-label="Открыть предложения"></a><span class="stat-serial">02 / КП</span></article>
      <article class="stat stat-teal stat-clickable"><div class="stat-top"><span>Клиенты в работе</span><span class="stat-icon is-action"><span class="stat-icon-copy"><small>Резерв</small><strong>${reserved} из ${clientTotal}</strong></span><span class="stat-affordance">${icon('arrow')}</span></span></div><div class="stat-value">${String(clientTotal).padStart(2, '0')}</div><div class="stat-foot"><span class="delta">${reserved} с резервом</span><span>в текущей выборке</span></div><div class="stat-micro"><span class="stat-micro-head"><span>Доля резервов</span><strong>${ratio(reserved, clientTotal)}%</strong></span><span class="stat-meter"><i style="width:${ratio(reserved, clientTotal)}%"></i></span></div><a class="stat-link" href="#clients" aria-label="Открыть клиентов"></a><span class="stat-serial">03 / CRM</span></article>
      <article class="stat stat-coral stat-clickable"><div class="stat-top"><span>Требуют внимания</span><span class="stat-icon is-action"><span class="stat-icon-copy"><small>Фокус</small><strong>${attentionTotal} задач</strong></span><span class="stat-affordance">${icon('arrow')}</span></span></div><div class="stat-value">${String(attentionTotal).padStart(2, '0')}</div><div class="stat-foot"><span>${pending} на согласовании</span></div><div class="stat-micro"><span class="stat-micro-head"><span>Согласование</span><strong>${pending} из ${attentionTotal}</strong></span><span class="stat-meter"><i style="width:${ratio(pending, attentionTotal)}%"></i></span></div><button class="stat-link" data-action="notifications" aria-label="Открыть приоритеты"></button><span class="stat-serial">04 / Фокус</span></article>
    </div>`;
  }
  function chart(detailed = false) {
    const r = Domain.report(state.period, state.project);
    const values = r.current.map(v => v / 1000000), previous = r.previous.map(v => v / 1000000);
    const max = Math.max(...values, ...previous, 1) * 1.2;
    const left = 39, bottom = 166, height = 143, width = 570, step = (width - left) / values.length;
    const lines = Array.from({ length: 5 }, (_, i) => {
      const y = 23 + i * height / 4;
      return `<line class="gridline" x1="${left}" y1="${y}" x2="${width}" y2="${y}"/><text x="2" y="${y + 4}">${dec(max * (1 - i / 4))}</text>`;
    }).join('');
    const bars = values.map((v, i) => {
      const x = left + step * i + step / 2, bw = Math.min(25, step * .28), h = v / max * height, ph = previous[i] / max * height;
      return `<g><rect class="previous-bar" x="${x - bw - 2}" y="${bottom - ph}" width="${bw}" height="${ph}" rx="4"/><rect class="bar" x="${x + 2}" y="${bottom - h}" width="${bw}" height="${h}" rx="4"><title>${r.labels[i]}: ${money(r.current[i])}; предыдущий период ${money(r.previous[i])}</title></rect><text x="${x}" y="190" text-anchor="middle">${r.labels[i]}</text></g>`;
    }).join('');
    return `<article class="card sales-card"><div class="card-header"><div><h2>Объём продаж</h2></div>${!detailed ? `<button class="icon-button" data-action="chart-details" aria-label="Таблица данных продаж">${icon('arrow-up-right')}</button>` : ''}</div><div class="sales-chart"><div class="chart-meta"><div class="chart-total"><small>Итого за период</small><strong>${dec(r.total / 1000000)} <span>млн ₽</span></strong></div><span class="delta">${dec(r.delta)}%</span><div class="legend"><span><i></i>Этот период</span><span><i></i>Предыдущий</span></div></div><svg class="chart-svg" viewBox="0 0 586 202" role="img" aria-label="${r.label}. Объём продаж — ${money(r.total)}. Точные значения доступны в таблице отчёта.">${lines}${bars}</svg><div class="chart-note">Заключённые договоры · сводка ERP</div></div></article>`;
  }
  function priorityList() {
    const a = Domain.attention(state.project), rows = [];
    a.risks.forEach(p => rows.push(`<button class="priority-item" data-action="project" data-id="${p.id}"><span class="priority-body"><small class="priority-kicker">Стройка · 14 дней</small><strong>${esc(p.name)}: риск по срокам</strong><span>Прогноз ключей — ${p.forecast}<br>Поставка ЖБИ задержана</span></span>${icon('chevron-right')}</button>`));
    if (a.pending.length) rows.push(`<a class="priority-item" href="#approvals"><span class="priority-body"><small class="priority-kicker">Согласование · ${a.pending.length}</small><strong>Запросы на скидку</strong><span>${D.actor.role === 'lead' ? 'Проверьте расчёт и примите решение' : 'Добавьте обоснование для руководителя'}</span></span>${icon('chevron-right')}</a>`);
    if (a.unnotified.length) rows.push(`<button class="priority-item" data-action="notification" data-client="${a.unnotified[0].id}" data-id="${a.unnotified[0].projectId}"><span class="priority-body"><small class="priority-kicker">CRM · сообщение</small><strong>Подготовить уведомление</strong><span>${esc(a.unnotified[0].name)}<br>Обновлён прогноз передачи ключей</span></span>${icon('chevron-right')}</button>`);
    return rows.join('') || `<div class="calm-state">${icon('circleCheck')}<h3>Открытых задач нет</h3><p>Для выбранного объекта нет открытых задач.</p></div>`;
  }
  function priorities() {
    return `<article class="card priorities"><div class="card-header"><div><h2>Требуют внимания <span class="count-pill">${Domain.attention(state.project).total}</span></h2></div><button class="icon-button" data-action="notifications" aria-label="Все задачи">${icon('arrow-up-right')}</button></div><div class="priority-list">${priorityList()}</div><div class="priorities-footer"><span>На основе текущих данных</span><span>10:42</span></div></article>`;
  }
  function projectRows() {
    return D.projects.filter(p => scoped(p.id)).map(p => `<button class="project-row" data-action="project" data-id="${p.id}"><span class="project-name"><span class="building-thumb ${p.color}">${icon('building')}</span><span><strong>${esc(p.name)}</strong><small>${p.building}</small></span></span><span class="project-progress"><span class="progress-label"><span>Готовность</span><strong>${p.progress}%</strong></span><span class="progress-track ${p.risk}"><span style="width:${p.progress}%"></span></span></span><span class="project-status">${tag(p.risk === 'risk' ? 'Есть риск' : 'По графику', p.risk === 'risk' ? 'orange' : 'green', true)}<small>${p.forecast}</small></span></button>`).join('');
  }
  function dossierSection(projects) {
    const cards = projects.map(p => {
      const documents = [
        ['schedule', 'calendar', 'График', `${p.progress}% готовности`],
        ['materials', 'database', 'Материалы', `${p.materials}% в наличии`],
        ['changes', p.risk === 'risk' ? 'alert' : 'documentCheck', 'Изменения', p.risk === 'risk' ? 'Есть новый риск' : 'Без изменений']
      ];
      return `<article class="dossier-folder ${p.color} ${p.risk === 'risk' ? 'has-risk' : ''}">
        <div class="dossier-stage">
          <div class="dossier-back" aria-hidden="true"><span></span></div>
          <button class="dossier-front" data-action="dossier-toggle" data-id="${p.id}" aria-expanded="false" aria-controls="dossier-${p.id}">
            <span class="dossier-front-line"><span class="dossier-mark">${icon('building')}</span><span><strong>${esc(p.name)}</strong><small>${p.building} · 3 документа</small></span></span>
            <span class="dossier-hint">Открыть досье ${icon('arrow')}</span>
          </button>
          <div class="dossier-files" id="dossier-${p.id}">${documents.map(([type, glyph, title, meta], index) => `<button class="dossier-file" style="--file:${index}" data-action="document" data-id="${p.id}" data-doc="${type}" aria-label="${esc(title)}: ${esc(p.name)}"><span class="dossier-file-icon">${icon(glyph)}</span><strong>${esc(title)}</strong><small>${esc(meta)}</small></button>`).join('')}</div>
        </div>
      </article>`;
    }).join('');
    return `<section class="dossier-section" aria-labelledby="dossier-title"><div class="section-heading dossier-heading"><div><h2 id="dossier-title">Досье объектов</h2></div><span>Графики, поставки и изменения</span></div><div class="dossier-grid">${cards}</div></section>`;
  }
  function assistantCard() {
    return `<article class="assistant-card assistant-information-only"><canvas class="assistant-matrix" data-matrix="assistant" aria-hidden="true"></canvas><div class="assistant-copy-glass"><div class="assistant-title"><strong>Рабочий помощник</strong><small>Демо</small></div><h3>Помощник по продажам</h3><p>Проверяет данные строительства, финансовую модель и контекст клиента.</p><div class="assistant-data-sources"><span><small>ERP</small><strong>Сроки и остатки</strong></span><span><small>CRM</small><strong>Контекст клиента</strong></span><span><small>Модель</small><strong>Цена и скидка</strong></span></div><button class="assistant-suggestion" data-action="ai" data-question="Что сегодня требует внимания?">Показать приоритеты ${icon('arrow')}</button></div><form class="assistant-input" id="assistant-form"><input name="question" aria-label="Вопрос ассистенту" placeholder="Спросите о квартире или сроках…" maxlength="500" required><button type="submit" aria-label="Задать вопрос">${icon('arrow')}</button></form></article>`;
  }
  function filteredProposals() {
    const needle = state.search.trim().toLocaleLowerCase('ru');
    return D.proposals.filter(q => scoped(apartment(q.apartmentId).projectId) && (state.status === 'all' || q.status === state.status) && `${q.id} ${client(q.clientId).name} ${project(apartment(q.apartmentId).projectId).name}`.toLocaleLowerCase('ru').includes(needle));
  }
  function proposalTable(items, compact = false) {
    return `<article class="card table-card">${compact ? `<div class="card-header"><h2>Последние предложения</h2><a class="text-link" href="#proposals">Все предложения ${icon('arrow')}</a></div>` : ''}${items.length ? `<div class="table-scroll" tabindex="0" role="region" aria-label="Таблица предложений"><table><thead><tr><th>Клиент</th><th>Объект и квартира</th><th>Стоимость</th><th>Скидка</th><th>Статус</th><th>Дата</th><th><span class="sr-only">Открыть</span></th></tr></thead><tbody>${items.map(q => { const c = client(q.clientId), a = apartment(q.apartmentId), p = project(a.projectId); return `<tr><td><button class="client-cell" data-action="client" data-id="${c.id}">${avatar(c)}<span><strong>${esc(c.name)}</strong><small>${q.id}</small></span></button></td><td>${esc(p.name)}<span class="cell-secondary">${a.rooms}-комн. · ${dec(a.area)} м² · №${a.number}</span></td><td class="price-cell">${money(cost(q).total)}</td><td>${dec(q.discount)}%</td><td>${qTag(q)}</td><td>${date(q.date).slice(0, 5)}</td><td><button class="table-action" data-action="proposal" data-id="${q.id}" aria-label="Открыть ${q.id}">${icon('arrow-up-right')}</button></td></tr>`; }).join('')}</tbody></table></div>` : empty('Предложения не найдены.', 'Измените запрос или сбросьте фильтры.', reset())}<div class="table-foot"><span>${compact ? 'Последние ' + items.length : 'Найдено: ' + items.length}</span><span>Финмодель ${D.model.version}</span></div></article>`;
  }
  function draftBanner() {
    const drafts = D.quoteDrafts.filter(d => !d.apartmentId || scoped(apartment(d.apartmentId)?.projectId));
    return drafts.length ? `<div class="draft-banner"><span class="draft-symbol">${icon('edit')}</span><div><strong>Есть незавершённое предложение.</strong><p>Черновиков в сеансе: ${drafts.length}. Продолжите с сохранённых условий.</p></div>${btn('draft-list', 'Продолжить', 'arrow', 'small')}</div>` : '';
  }
  function overviewHero() {
    const focus = Domain.attention(state.project).total;
    const visibleProjects = D.projects.filter(p => scoped(p.id));
    const available = visibleProjects.reduce((sum, p) => sum + p.available, 0);
    const spotlight = visibleProjects.find(p => p.risk === 'risk') || visibleProjects[0];
    const spotlightTitle = spotlight.risk === 'risk' ? `${spotlight.name}: срок под наблюдением` : `${spotlight.name}: работы по графику`;
    const spotlightText = spotlight.risk === 'risk' ? spotlight.reason : `${spotlight.stage} · готовность ${spotlight.progress}%. ${spotlight.reason}`;
    return `<section class="overview-hero" aria-labelledby="overview-title"><canvas class="overview-banner-matrix" data-matrix="overview" aria-hidden="true"></canvas>
      <div class="hero-panel">
        <div class="hero-content">
          <div class="hero-meta"><span class="hero-badge"><span>ДСК</span>Пространство продаж</span><span class="hero-context">${esc(state.project === 'all' ? 'Все объекты' : project(state.project).name)} · демо</span></div>
          <div class="hero-copy"><h1 id="overview-title">Продажи и стройка в одном контуре</h1>
            <p class="hero-description">Данные ERP, риски сроков и клиентские предложения — в одной рабочей системе.</p>
            <div class="hero-actions">${btn('new-proposal', 'Создать предложение', 'plus', 'hero-primary')}${btn('notifications', focus ? 'Фокус дня · ' + focus : 'Приоритеты на сегодня', 'arrow', 'hero-secondary')}</div>
          </div>
          <div class="hero-shortcuts" aria-label="Быстрые переходы">
            <a href="#clients"><span>Клиенты в работе</span><strong>${D.clients.filter(c => scoped(c.projectId)).length}</strong></a>
            <a href="#apartments"><span>Свободно в ERP</span><strong>${available}</strong></a>
            <a href="#construction"><span>Объекты</span><strong>${visibleProjects.length}</strong></a>
          </div>
        </div>
        <aside class="hero-visual" aria-label="Оперативный вывод по строительству">
          <img class="hero-banner-art" src="./banner-overview-v1.webp" alt="" width="820" height="547" fetchpriority="high">
          <div class="hero-insight"><span class="hero-insight-label">Оперативный вывод</span><strong>${esc(spotlightTitle)}</strong><p>${esc(spotlightText)}</p><button data-action="project" data-id="${spotlight.id}"><span>Открыть объект</span>${icon('arrow')}</button></div>
        </aside>
      </div>
    </section>`;
  }
  views.overview = () => overviewHero() + `<div class="overview-summary"><h2>Ключевые показатели</h2>${btn('report', 'Отчёт', 'download')}</div>` + filterBar() + draftBanner() + statistics() + `<div class="middle-grid">${chart()}${priorities()}</div><div class="manager-construction"><article class="card construction-overview"><div class="card-header"><div><h2>Состояние объектов</h2></div><a class="text-link" href="#construction">Все объекты ${icon('arrow')}</a></div>${projectRows()}</article></div>` + proposalTable(D.proposals.filter(q => scoped(apartment(q.apartmentId).projectId)).slice(0, 4), true);
  views.clients = () => {
    const query = state.search.trim().toLocaleLowerCase('ru');
    const items = D.clients.filter(c => scoped(c.projectId) && `${c.name} ${c.contact} ${c.phone} ${c.interest}`.toLocaleLowerCase('ru').includes(query));
    const visible = D.clients.filter(c => scoped(c.projectId));
    const reserved = visible.filter(c => D.apartments.some(a => a.status === 'reserved' && a.reservedBy === c.id)).length;
    const next = visible[0];
    const visits = `<section class="glass-reference-band visits-band"><canvas class="section-live-matrix" data-matrix="clients" aria-hidden="true"></canvas><div class="glass-reference-copy"><h2>От обращения до просмотра квартиры</h2><p>Пожелания, объект и следующий контакт остаются рядом с карточкой клиента.</p><div class="glass-reference-pills"><span><strong>${visible.length}</strong> клиентов</span><span><strong>${reserved}</strong> с резервом</span></div></div><div class="visit-widget" aria-label="План ближайших действий"><div class="visit-orbit" aria-hidden="true"></div><div class="visit-calendar"><div class="visit-days">${[['ПН','1'],['ВТ','2'],['СР','3'],['ЧТ','4'],['ПТ','5']].map(([day,date],i)=>`<span class="${i===2?'active':''}"><small>${day}</small><strong>${date}</strong></span>`).join('')}</div></div><div class="visit-action"><span class="visit-clock">${icon('calendar')}</span><div><strong>Следующий контакт</strong><small>${next ? esc(next.name)+' · '+esc(next.interest) : 'Клиент не выбран'}</small></div>${next ? btn('client','Открыть карточку','arrow','primary',`data-id="${next.id}"`) : btn('edit-client','Добавить клиента','plus','primary')}</div></div></section>`;
    return heading('Клиенты', 'Пожелания, контекст и следующий шаг по каждому обращению.', true, btn('edit-client', 'Добавить клиента', 'users')) + visits + `<div class="section-toolbar"><label class="input-search">${icon('search')}<input id="list-search" value="${esc(state.search)}" placeholder="Имя, email или телефон" aria-label="Поиск клиента"></label>${projectSelect()}<span class="filter-note">Найдено: ${items.length}</span></div><article class="card table-card">${items.length ? `<div class="table-scroll" tabindex="0" role="region" aria-label="Список клиентов"><table><thead><tr><th>Клиент</th><th>Интерес</th><th>Жилой комплекс</th><th>Этап сделки</th><th>Контакт</th><th><span class="sr-only">Карточка</span></th></tr></thead><tbody>${items.map(c => `<tr><td><button class="client-cell" data-action="client" data-id="${c.id}">${avatar(c)}<span><strong>${esc(c.name)}</strong><small>${esc(c.contact || c.phone)}</small></span></button></td><td>${esc(c.interest)}</td><td>${esc(project(c.projectId).name)}</td><td>${tag(c.stage, c.stage === 'Бронирование' ? 'green' : c.stage.includes('Согласование') ? 'orange' : 'blue')}</td><td>${esc(c.last)}</td><td><button class="table-action" data-action="client" data-id="${c.id}" aria-label="Карточка: ${esc(c.name)}">${icon('arrow-up-right')}</button></td></tr>`).join('')}</tbody></table></div>` : empty('Такого клиента пока нет.', 'Проверьте написание или добавьте нового клиента.', reset() + btn('edit-client', 'Добавить клиента', 'plus', 'primary'))}</article>`;
  };
  views.apartments = () => {
    let items = D.apartments.filter(a => scoped(a.projectId) && (state.rooms === 'all' || a.rooms === Number(state.rooms)) && (state.availability === 'all' || a.status === state.availability) && (!state.budget || a.price <= Number(state.budget) * 1000000));
    if (state.sort === 'price-up') items.sort((a, b) => a.price - b.price);
    if (state.sort === 'price-down') items.sort((a, b) => b.price - a.price);
    if (state.sort === 'area') items.sort((a, b) => b.area - a.area);
    const available = items.filter(a => a.status === 'available').length;
    const averageArea = items.length ? Math.round(items.reduce((sum, a) => sum + a.area, 0) / items.length) : 0;
    const firstApartment = items[0];
    const visual = editorialBand('apartments', 'Планировка сразу в контексте', 'Сравнивайте площадь, этаж, срок передачи и стоимость без перехода между экранами.', [`${items.length} вариантов`, `${available} свободно`, averageArea ? `${averageArea} м² средняя площадь` : 'Настройте фильтры'], 'Подбор по планировке', 'Площадь, этаж и срок передачи', firstApartment ? btn('apartment', 'Открыть квартиру', 'arrow', 'banner-action', `data-id="${firstApartment.id}"`) : '');
    return heading('Каталог квартир', 'Поиск по объекту, бюджету, площади и текущей доступности.', D.actor.role !== 'client') + visual + `<div class="catalog-toolbar"><div class="section-toolbar">${projectSelect()}<div class="chip-list" role="group" aria-label="Количество комнат">${[['all', 'Все'], ['1', '1-комн.'], ['2', '2-комн.'], ['3', '3-комн.']].map(([v, t]) => `<button class="chip ${state.rooms === v ? 'active' : ''}" data-rooms="${v}" aria-pressed="${state.rooms === v}">${t}</button>`).join('')}</div><label class="budget-input"><span>До</span><input id="budget-filter" type="number" min="1" max="100" step="0.1" value="${esc(state.budget)}" placeholder="Любой" aria-label="Максимальная базовая цена в миллионах рублей"><span>млн ₽</span></label></div><div class="section-toolbar secondary-toolbar"><label class="checkbox-filter"><input id="availability-filter" class="toggle-control" type="checkbox" role="switch" ${state.availability === 'available' ? 'checked' : ''}>Только свободные</label><label class="sort-select"><span>Сортировка</span><select id="sort-filter">${[['recommended', 'По умолчанию'], ['price-up', 'Сначала дешевле'], ['price-down', 'Сначала дороже'], ['area', 'Сначала просторнее']].map(([v, t]) => `<option value="${v}" ${state.sort === v ? 'selected' : ''}>${t}</option>`).join('')}</select></label><span class="filter-note">Найдено: ${items.length}</span>${reset()}</div></div><div class="catalog-grid">${apartmentCards(items)}</div>${!items.length ? `<article class="card">${empty('Подходящих квартир нет.', 'Увеличьте бюджет или измените количество комнат. Цена указана до скидки.', reset())}</article>` : ''}`;
  };
  views.proposals = () => {
    const items = filteredProposals();
    const ready = items.filter(q => q.status === 'ready').length;
    const visual = editorialBand('proposals', 'Условия собраны в одном документе', 'Стоимость, скидка, отделка и срок передачи фиксируются по текущим данным.', [`${items.length} предложений`, `${ready} готовы`, `Модель ${D.model.version}`], 'Готовое предложение', 'Стоимость, скидка и комплектация', items[0] ? btn('proposal', 'Открыть КП', 'arrow', 'banner-action', `data-id="${items[0].id}"`) : btn('new-proposal', 'Создать КП', 'plus', 'banner-action'));
    return heading('Коммерческие предложения', 'Расчёт, согласование скидки и статус резерва.', true, btn('report', 'Выгрузить', 'download')) + visual + draftBanner() + `<div class="section-toolbar"><label class="input-search">${icon('search')}<input id="list-search" value="${esc(state.search)}" placeholder="Клиент, объект или номер КП" aria-label="Поиск предложений"></label>${projectSelect()}<label class="select-wrap"><select id="status-filter" aria-label="Статус предложения"><option value="all">Все статусы</option>${Object.entries(statuses).map(([v, [t]]) => `<option value="${v}" ${state.status === v ? 'selected' : ''}>${t}</option>`).join('')}</select>${icon('chevron-down')}</label></div>` + proposalTable(items);
  };
  views.construction = () => {
    const projects = D.projects.filter(p => scoped(p.id));
    const average = Math.round(projects.reduce((sum, p) => sum + p.progress, 0) / projects.length);
    const atRisk = projects.filter(p => p.risk === 'risk').length;
    const cards = projects.map(p => `<article class="card project-detail-card"><div class="apartment-card-top"><span class="building-thumb ${p.color}">${icon('building')}</span>${tag(p.risk === 'risk' ? 'Есть риск' : 'По графику', p.risk === 'risk' ? 'orange' : 'green', true)}</div><h2>${esc(p.name)}</h2><p>${esc(p.address)}<br>${p.building} · ${p.stage}</p><div class="progress-label"><span>Готовность</span><strong>${p.progress}%</strong></div><div class="progress-track ${p.risk}"><span style="width:${p.progress}%"></span></div>${kv('Договорный срок', p.planned)}${kv('Прогноз ключей', p.forecast)}${kv('Материалы в наличии', p.materials + '%')}${kv('Свободных квартир в ERP', p.available)}${btn('project', 'График и детали', 'arrow', 'wide', `data-id="${p.id}"`)}</article>`).join('');
    const timeline = `<article class="card padded timeline-card"><div class="card-header plain"><h2>Что изменилось</h2>${source('Строительный контроль')}</div>${scoped('p2') ? `<div class="timeline-item risk">${icon('alert')}<div><strong>Новая высота · сдвиг поставки перекрытий</strong><p>Ожидается 44 плиты. Новая дата поставки — 19 сентября. Прогноз ключей: III квартал 2027.</p><small>5 сентября, 09:30</small>${btn('project', 'Открыть риск', 'arrow', 'subtle', 'data-id="p2"')}</div></div>` : ''}${scoped('p3') ? `<div class="timeline-item">${icon('circleCheck')}<div><strong>Речной квартал · инженерные системы приняты</strong><p>Проверка водоснабжения завершена, замечаний нет.</p><small>4 сентября, 16:10</small></div></div>` : ''}<div class="timeline-item">${icon('file')}<div><strong>Планировки без изменений</strong><p>В текущем срезе изменений конфигурации квартир не зарегистрировано.</p><small>Проектная документация · 5 сентября, 10:42</small></div></div></article>`;
    const visual = editorialBand('construction', 'Фактический ритм объектов', 'График работ, обеспеченность материалами и прогноз передачи ключей сверяются в одном срезе.', [`${projects.length} объекта`, `${average}% средняя готовность`, atRisk ? `${atRisk} риск срока` : 'Рисков срока нет'], 'Срез по объекту', 'График, материалы и прогноз ключей', projects[0] ? btn('project', 'Открыть объект', 'arrow', 'banner-action', `data-id="${projects[0].id}"`) : '');
    return heading('Ход строительства', 'Готовность объектов, материалы, сроки и зарегистрированные изменения.', false) + visual + `<div class="section-toolbar">${projectSelect()}<span class="filter-note">Срез ERP · 5 сентября, 10:42</span></div><div class="project-cards">${cards}</div>` + dossierSection(projects) + timeline;
  };
  views.approvals = () => {
    const items = D.proposals.filter(q => q.status === 'pending' && scoped(apartment(q.apartmentId).projectId));
    const decisions = D.proposals.filter(q => q.approval && scoped(apartment(q.apartmentId).projectId));
    const visual = editorialBand('approvals', 'Скидка видна вместе с основанием', 'Руководитель сразу видит запрос, лимит модели и данные по объекту.', [`${items.length} ожидают`, `${decisions.length} решения`, `Лимиты ${D.model.version}`], 'Решение по скидке', 'Лимит, обоснование и итоговая цена', items[0] ? btn('approval', 'Открыть запрос', 'arrow', 'banner-action', `data-id="${items[0].id}"`) : '');
    return heading('Согласование скидок', 'Запросы, лимиты финансовой модели и решения руководителя.', false, btn('profile', D.actor.role === 'lead' ? 'Руководитель · демо' : 'Менеджер · демо', 'shield')) + visual + `<div class="info-strip">${icon('shield')}<span>${D.actor.role === 'lead' ? 'Вы можете принять решение по запросам другого сотрудника.' : 'Добавьте обоснование. Решение принимает руководитель.'} Для проверки всего сценария смените демо-роль в профиле.</span></div><div class="section-toolbar">${projectSelect()}<span class="filter-note">Ожидают решения: ${items.length}</span></div><div class="approval-list">${items.map(q => { const a = apartment(q.apartmentId); return `<article class="card approval-card"><div><span class="section-kicker">${q.id}</span><h3>${esc(client(q.clientId).name)}</h3><p>${esc(project(a.projectId).name)} · №${a.number}</p>${q.reason ? tag('Обоснование добавлено', 'green') : tag('Нужно обоснование', 'orange')}</div><div class="approval-number exceeded">${dec(q.discount)}<span>%</span><small>Запрошено</small></div><div class="approval-number">${q.snapshot.limit}<span>%</span><small>Лимит модели</small></div><div class="approval-action"><strong>${money(cost(q).total)}</strong>${btn('approval', D.actor.role === 'lead' ? 'Принять решение' : 'Обоснование', 'arrow', '', `data-id="${q.id}"`)}</div></article>`; }).join('')}</div>${!items.length ? `<article class="card">${empty('Все запросы обработаны.', 'Предложения с превышением лимита появятся здесь.', btn('new-proposal', 'Создать предложение', 'plus', 'primary'))}</article>` : ''}${decisions.length ? `<div class="section-heading"><h2>История решений</h2><span>${decisions.length}</span></div>${proposalTable(decisions)}` : ''}`;
  };
  views.analytics = () => {
    const clients = D.clients.filter(c => scoped(c.projectId));
    const observed = clients.filter(c => c.objection).map(c => ({ c, result: Domain.analyzeTranscript(c.objection, c.id) }));
    const findings = new Map();
    observed.forEach(({ result }) => result.findings.forEach(f => { const old = findings.get(f.key) || { title: f.title, count: 0 }; old.count++; findings.set(f.key, old); }));
    const attention = Domain.attention(state.project);
    const top = [...findings.values()].sort((a,b) => b.count-a.count)[0];
    const signals = [
      {label:'Диалоги', title:top ? top.title : 'Диалогов для анализа пока нет', copy:top ? `Тема встречается в ${top.count} из ${observed.length} фрагментов. Откройте диалог, чтобы проверить цитату и рекомендацию.` : 'Добавьте фрагмент разговора в карточку клиента.', source:'CRM · локальный разбор', tone:'calm', action:clients.length ? btn('analysis','Разобрать диалог','arrow','',`data-id="${clients[0].id}"`) : ''},
      {label:'Строительство', title:attention.risks.length ? `Объектов с риском по срокам: ${attention.risks.length}` : 'Рисков по срокам не отмечено', copy:attention.risks.length ? `Проверьте прогноз передачи ключей: ${attention.risks.map(p=>p.name).join(', ')}. Клиентов без подготовленного уведомления: ${attention.unnotified.length}.` : 'Проверьте актуальный график перед разговором с клиентом.', source:'ERP · текущий срез', tone:attention.risks.length ? 'risk' : 'calm', action:'<a class="button" href="#construction">Открыть строительство</a>'},
      {label:'Скидки', title:`Предложений на согласовании: ${attention.pending.length}`, copy:attention.pending.length ? 'Индивидуальные скидки превышают лимит. До решения руководителя условия остаются предварительными.' : 'Открытых запросов на индивидуальную скидку в этой выборке нет.', source:'Финансовая модель '+D.model.version, tone:attention.pending.length ? 'risk' : 'calm', action:'<a class="button" href="#approvals">Открыть согласования</a>'}
    ];
    const visual = `<section class="matrix-insights" data-matrix-tone="calm" aria-label="Выводы по текущим данным"><canvas class="analytics-banner-matrix" data-matrix="analytics" aria-hidden="true"></canvas><div class="matrix-insight-copy"><div class="matrix-switch" role="group" aria-label="Тип вывода">${signals.map((v,i)=>`<button type="button" data-action="matrix-signal" data-index="${i}" data-tone="${v.tone}" aria-pressed="${i===0}" aria-controls="matrix-signal-${i}">${v.label}</button>`).join('')}</div><div class="matrix-signal-content" aria-live="polite">${signals.map((v,i)=>`<div id="matrix-signal-${i}" class="matrix-signal" ${i ? 'hidden' : ''}><h2>${esc(v.title)}</h2><p>${esc(v.copy)}</p><div class="matrix-source">${esc(v.source)}</div>${v.action}</div>`).join('')}</div></div><div class="matrix-insight-visual art-only" aria-hidden="true"><img class="analytics-banner-art" src="./banner-analytics-v1.webp" alt="" width="820" height="547" loading="eager" fetchpriority="high" decoding="async"></div></section>`;
    return heading('Демонстрационный раздел', '(не будет присутствовать в итоговом экземпляре проекта, существует только для демонстрации функционала вэб-приложения)', false, clients.length ? btn('analysis', 'Разобрать диалог', 'sparkles', 'primary', `data-id="${clients[0].id}"`) : '') + visual + `<div class="section-toolbar">${projectSelect()}<span class="filter-note">Локальный демо-анализ · ${observed.length} фрагментов</span></div><div class="analytics-grid"><article class="card padded"><h2>Основные темы</h2>${[...findings.values()].sort((a, b) => b.count - a.count).map(f => `<div class="objection-row"><div class="objection-label"><span>${f.title}</span><strong>${f.count} / ${observed.length}</strong></div><div class="progress-track"><span style="width:${observed.length ? f.count / observed.length * 100 : 0}%"></span></div></div>`).join('') || empty('Пока нет диалогов.', 'Добавьте текст разговора в карточке клиента.')}<p class="dialog-caption">Один фрагмент может затрагивать несколько тем. Это разбор демо-выборки, а не оценка качества работы менеджера.</p></article><article class="card padded"><h2>Порядок подготовки ответа</h2><div class="insight"><span class="insight-number">01</span><div><h3>Сверить ожидания со строительством</h3><p>Разделяйте договорный срок и текущий прогноз. Указывайте источник и дату среза.</p>${source('ERP / проектная документация')}</div></div><div class="insight"><span class="insight-number">02</span><div><h3>Проверить экономику предложения</h3><p>Скидка действует на квартиру. Отделка и парковка рассчитываются отдельно.</p>${source('Финансовая модель ' + D.model.version)}</div></div><div class="insight"><span class="insight-number">03</span><div><h3>Обозначить недостающие сведения</h3><p>Если нет ставки банка или предложения конкурента — сначала запросите подтверждённые данные.</p></div></div></article></div><div class="section-heading"><h2>Диалоги для разбора</h2><span>Выберите контекст клиента</span></div><div class="dialogue-list">${clients.map(c => `<button class="card dialogue-card" data-action="analysis" data-id="${c.id}"><span class="client-cell">${avatar(c)}<span><strong>${esc(c.name)}</strong><small>${esc(project(c.projectId).name)}</small></span></span><span class="dialogue-quote">${c.objection ? '«' + esc(c.objection) + '»' : 'Добавьте фрагмент разговора для анализа'}</span><span class="dialogue-arrow">${icon('arrow-up-right')}</span></button>`).join('')}</div>`;
  };
  window.Dsk.viewHelpers = { apartmentCards, projectRows, projectSelect, filterBar, chart, priorityList, proposalTable, filteredProposals, draftBanner };
})();
